# Generated by Django 4.1.3 on 2022-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurritoBowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('small', models.CharField(max_length=5)),
                ('large', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BurritoWrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('small', models.CharField(max_length=5)),
                ('large', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('toppingsList', models.CharField(default='', max_length=100)),
                ('approved', models.CharField(default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('small', models.CharField(max_length=5)),
                ('large', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Subs',
            },
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Toppings',
            },
        ),
    ]
